//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fendahl1ProjectMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fendyl_pprojectbEntities : DbContext
    {
        public fendyl_pprojectbEntities()
            : base("name=fendyl_pprojectbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TableInvoiceDetail> TableInvoiceDetails { get; set; }
        public virtual DbSet<TableProduct> TableProducts { get; set; }
        public virtual DbSet<TableProductCategory> TableProductCategories { get; set; }
        public virtual DbSet<TableProductGSTDetail> TableProductGSTDetails { get; set; }
    }
}
