//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fendahl1ProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableProductCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableProductCategory()
        {
            this.TableInvoiceDetails = new HashSet<TableInvoiceDetail>();
            this.TableProducts = new HashSet<TableProduct>();
        }
    
        public int Product_Category_ID { get; set; }
        public string Product_Type_Name { get; set; }
        public Nullable<int> Product_Gst_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableInvoiceDetail> TableInvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableProduct> TableProducts { get; set; }
        public virtual TableProductGSTDetail TableProductGSTDetail { get; set; }
    }
}
