//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fendahl1ProjectMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableInvoiceDetail
    {
        public int Invoice_Detail_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Contact { get; set; }
        public Nullable<int> Product_Category_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Resedential_Type_ID { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST_Value { get; set; }
        public Nullable<decimal> SGST_Value { get; set; }
        public Nullable<decimal> IGST_Value { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
    
        public virtual TableProductCategory TableProductCategory { get; set; }
        public virtual TableProduct TableProduct { get; set; }
    }
}
